[package]
name = "journal-maker-rs"
version = "0.1.0"
authors = ["Antonio Yang <antonio.yang@siliconmotion.com.tw>"]

[dependencies]
actix-web = "^0.7.14"
futures = "^0.1.21"
serde = "^1.0.81"
serde_json = "^1.0.33"
serde_derive = "^1.0.81"
jsonwebtoken = "^5.0.1"
chrono = "^0.4.6"
sha2 = "^0.8.0"
